# Generated by Django 2.2.3 on 2019-08-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_name', models.TextField()),
                ('settings_pic', models.TextField()),
                ('settings_pic_url', models.TextField()),
                ('settings_head', models.TextField()),
                ('settings_title', models.TextField()),
            ],
        ),
    ]
