# Generated by Django 2.2.3 on 2019-09-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanager',
            name='upass',
        ),
    ]
