# Generated by Django 2.2.3 on 2019-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_remove_usermanager_upass'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanager',
            name='group',
            field=models.TextField(default='admin_level_1'),
        ),
    ]
