# Generated by Django 2.2.3 on 2019-07-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=30)),
                ('last_name', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
