# Generated by Django 2.2.3 on 2019-07-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
