# Generated by Django 2.2.3 on 2019-10-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.TextField()),
                ('menu_name', models.TextField()),
                ('menu_id', models.IntegerField()),
            ],
        ),
    ]
