# Generated by Django 2.2.3 on 2019-07-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_titel', models.CharField(max_length=30)),
                ('news_pic', models.TextField()),
                ('news_url', models.TextField()),
                ('news_short_txt', models.TextField()),
                ('news_body_txt', models.TextField()),
            ],
        ),
    ]
