# Generated by Django 2.2.3 on 2019-08-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.TextField()),
                ('menu_titel', models.TextField()),
                ('menu_link', models.TextField()),
            ],
        ),
    ]
