# Generated by Django 2.2.3 on 2019-10-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_link',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_titel',
        ),
    ]
